export const currencies = [
  { name: "USD" },
  { name: "EUR" },
  { name: "GBP" },
  { name: "CNY" },
  { name: "AUD" },
  { name: "CAD" },
  { name: "CHF" },
  { name: "JPY" },
  { name: "INR" },
  { name: "JEP" },
  { name: "MVR" },
  { name: "NGN" },
  { name: "RSD" },
  { name: "RUB" },
  { name: "SCR" },
  { name: "SAR" },
  { name: "KZT" },
  { name: "KWD" },
  { name: "AED" },
  { name: "BND" },
];
